import { Bebas_Neue,  } from "next/font/google";
import "./globals.css";



const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Infinte Carousel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
